- uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          BLOCKS: â–‘â–’â–“â–ˆ
          CODE_LANG: python
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
          # ðŸ‘‡ This is the fixed line:
          TARGET_PATH: "adixyaxo.md"
